from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class JobType(StrEnum):
    PANORAMA_STITCH = "PANORAMA_STITCH"
    PANORAMA_QA = "PANORAMA_QA"
    PRIVACY_SCAN = "PRIVACY_SCAN"
    CAPTURE_VALIDATION = "CAPTURE_VALIDATION"
    CAPTURE_PACKAGE_VALIDATE = "CAPTURE_PACKAGE_VALIDATE"
    KEYFRAME_PROCESS = "KEYFRAME_PROCESS"
    DEPTH_FUSE = "DEPTH_FUSE"
    SURFACE_EXTRACT = "SURFACE_EXTRACT"
    ROOM_MODEL_INFER = "ROOM_MODEL_INFER"
    OPENING_INFER = "OPENING_INFER"
    MODEL_OPTIMIZE = "MODEL_OPTIMIZE"
    MODEL_QA = "MODEL_QA"
    MODEB_GEOMETRY = "MODEB_GEOMETRY"
    SCENE_ASSEMBLE = "SCENE_ASSEMBLE"
    ASSET_OPTIMIZE = "ASSET_OPTIMIZE"
    RENDER_PREVIEW = "RENDER_PREVIEW"
    RENDER_FINAL = "RENDER_FINAL"
    EXPORT_PARAMETRIC_SHELL_GLB = "EXPORT_PARAMETRIC_SHELL_GLB"
    EXPORT_MODEL = "EXPORT_MODEL"
    EXPORT_PLAN = "EXPORT_PLAN"
    EXPORT_SCHEDULE = "EXPORT_SCHEDULE"
    ROOM_SHELL = "ROOM_SHELL"


class ProcessRequest(BaseModel):
    jobId: str = Field(min_length=1)
    type: JobType
    payload: dict[str, Any]


class ProcessResponse(BaseModel):
    success: bool
    output: dict[str, Any]
